Instruction Exection for RV32-I R-type instructions
wadachi-ware/wadachi-cpu pull request #11
Opened 2021-02-12 10:34 UTC by proelbtn

RV32-I R-typeの命令を実行できるように実装を行いました

closes: #9

2021-02-12 10:58 UTC, ikanago commented on src/memory.rs
> +pub struct EmptyMemory {
メンバがないので `pub struct EmptyMemory;` でいいと思います

2021-02-12 10:59 UTC, ikanago commented on src/memory.rs
> +    fn read_inst(&self, addr: usize) -> u32 {
`addr` は未使用なので `_addr` にしておくと warning が出なくてよさそうです(下のふたつも同様)

2021-02-12 11:24 UTC, ikanago commented on src/memory.rs
> +    pub fn write_inst(&mut self, addr: usize, inst: u32) {
> The base ISA has been defined to have a little-endian memory system (仕様書p.5)

> We originally chose little-endian byte ordering for the RISC-V memory system (仕様書p.27)

とあるのでリトルエンディアンでよさそうなんですが，命令をビッグエンディアンで格納する理由はなんですか?

>  RISC-V base ISAs have either little-endian or big-endian memory systems (仕様書p.27)

ともあるのでそれでもよさそうなんですが

2021-02-12 11:41 UTC, ikanago requested changes
いくつかコメントしたので確認おねがいします!

2021-02-12 14:52 UTC, proelbtn commented on src/memory.rs
> +    pub fn write_inst(&mut self, addr: usize, inst: u32) {
命令列がメモリ上でどのように格納されるべきなのかについては正確な文献がなく、（自分の中の認識では）x86と同様にビッグエンディアンで格納してました。ですが、後者についても確信をもって「そう」と言える根拠がなかったり、x86とriscだと固定長命令か可変長命令かの違いもあるので、どうするのがいいか悩んでいます（他のエミュレータ等を参考にするのとかがいいですかね）

2021-02-13 02:33 UTC, ikanago commented on src/memory.rs
> +    pub fn write_inst(&mut self, addr: usize, inst: u32) {
はっきり分からないですよね…
とりあえず read/write ができればよさそうなのでこのままの実装にしておいて、コメントに「命令をビッグエンディアンで格納しているが標準的な方法はよく分からない」ことを書いておくことにしましょうか

2021-02-13 11:42 UTC, proelbtn commented
@ikanago 細かい部分の修正を行ってconflictの解消もしたので問題がなければマージしてもらって大丈夫です！

2021-02-13 11:55 UTC, ikanago approved these changes
マージします

2021-02-13 11:55 UTC, merged