I-Type instruction execution
wadachi-ware/wadachi-cpu pull request #24
Opened 2021-02-13 18:00 UTC by proelbtn

closes: 23

I-Typeの命令の実装を行いました

2021-02-14 01:59 UTC, ikanago commented on src/processor.rs
> +        if val & 0x800 != 0 {
即値の12ビット目が立っているかどうかを判別していることをコメントかなにかで補足しておくと分かりやすいかもしれないです

2021-02-14 02:19 UTC, ikanago commented on src/processor.rs
> +        let args: IType = IType {
`imm` が0でないパターンもあるほうが網羅的だと思いました

2021-02-14 02:39 UTC, ikanago commented on src/processor.rs
> +        assert_eq!(proc.pc, 0x68a);
`pc` の LSB を0にしていることを確認できたほうがいいと思います
例えば `imm`: 123, `rs1`: 456 で `pc`: 578 とかです

2021-02-14 02:40 UTC, ikanago requested changes
いくつかコメントしておきました!

2021-02-18 13:59 UTC, proelbtn commented
修正しました！

2021-02-18 14:02 UTC, ikanago approved these changes
👍

2021-02-18 14:07 UTC, merged