U-Type Instruction execution
wadachi-ware/wadachi-cpu pull request #42
Opened 2021-03-10 12:32 UTC by ikanago

close #12

2021-03-12 17:02 UTC, proelbtn requested changes

2021-03-12 17:02 UTC, proelbtn commented on src/processor.rs
> +        self.set_pc(imm);
AUIPC命令の解釈が間違っている気がします。Specificationには「AUIPC forms a 32-bit offset from the 20-bit U-immediate, filling in the lowest 12 bits with zeros, adds this offset to the address of the AUIPC instruction then places the result in register rd.」とあるので、以下のようなコードになる気がします。

```
let offset = (args.imm << 12) as u32;
let new_pc = self.pc + offset;
self.set_pc(new_pc);
self.write_reg(args.rd, new_pc);
```

2021-03-13 02:27 UTC, ikanago commented on src/processor.rs
> +        self.set_pc(imm);
確かに間違ってますね，直します

2021-03-13 06:42 UTC, proelbtn approved these changes

2021-03-13 06:45 UTC, merged